# Generated by Django 5.1.2 on 2025-01-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='photo',
            new_name='photos',
        ),
    ]
