# Generated by Django 5.1.2 on 2025-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_rename_photo_tweet_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='photos',
            new_name='photo',
        ),
    ]
